version: 0.{build}
image: Visual Studio 2017

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Microsoft.Linq.Translations.sln --verbosity m

build_script:
  - cmd: dotnet publish ./Microsoft.Linq.Translations.sln

artifacts:
  - path: ./Microsoft.Linq.Translations/bin/Debug/netstandard2.0/publish
    name: DotNetStandard2_0
    type: zip
